[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.0.0 --activate",
  "cd ../.. && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd ../../packages/db && npx prisma generate",
  "cd ../../apps/api && pnpm build"
]

[start]
cmd = "cd apps/api && node dist/main.js"

